manifest:
  version: 0.8

  projects:
    - name: zephyr
      # revision: v4.3.0
      # url: https://github.com/zephyrproject-rtos/zephyr
      url: https://github.com/BOJIT/zephyr
      # revision: main
      revision: driver/ch32v30x_ethernet

      import:
        file: west.yml
        path-prefix: deps
        name-allowlist:
          - cmsis_6
          - hal_wch

  self:
    path: samples
